// <auto-generated />
using System;
using JoinDev.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoinDev.Infra.Data.Migrations
{
    [DbContext(typeof(JoinDevContext))]
    partial class JoinDevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JoinDev.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LinkSource")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Links", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("PublicDescription")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalSpots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.ProjectRestrictedInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectsRestrictedInfo", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ThemeCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Themes", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProjectTheme", b =>
                {
                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThemesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectsId", "ThemesId");

                    b.HasIndex("ThemesId");

                    b.ToTable("ProjectTheme");
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<Guid>("MemberUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectsAsMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberUsersId", "ProjectsAsMemberId");

                    b.HasIndex("ProjectsAsMemberId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("ProjectUser1", b =>
                {
                    b.Property<Guid>("InterestedUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectsAsInterestedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InterestedUsersId", "ProjectsAsInterestedId");

                    b.HasIndex("ProjectsAsInterestedId");

                    b.ToTable("ProjectUser1");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.ProjectLink", b =>
                {
                    b.HasBaseType("JoinDev.Domain.Entities.Link");

                    b.Property<Guid>("ProjectRestrictedInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ProjectRestrictedInfoId");

                    b.ToTable("ProjectLinks", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.UserLink", b =>
                {
                    b.HasBaseType("JoinDev.Domain.Entities.Link");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("UserId");

                    b.ToTable("UserLinks", (string)null);
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.Project", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.User", "Creator")
                        .WithMany("ProjectsAsCreator")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.ProjectRestrictedInfo", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.Project", "Project")
                        .WithOne("ProjectRestrictedInfo")
                        .HasForeignKey("JoinDev.Domain.Entities.ProjectRestrictedInfo", "ProjectId")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectTheme", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .IsRequired();

                    b.HasOne("JoinDev.Domain.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemesId")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberUsersId")
                        .IsRequired();

                    b.HasOne("JoinDev.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsAsMemberId")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectUser1", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InterestedUsersId")
                        .IsRequired();

                    b.HasOne("JoinDev.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsAsInterestedId")
                        .IsRequired();
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.ProjectLink", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.Link", null)
                        .WithOne()
                        .HasForeignKey("JoinDev.Domain.Entities.ProjectLink", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("JoinDev.Domain.Entities.ProjectRestrictedInfo", "ProjectRestrictedInfo")
                        .WithMany("Links")
                        .HasForeignKey("ProjectRestrictedInfoId")
                        .IsRequired();

                    b.Navigation("ProjectRestrictedInfo");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.UserLink", b =>
                {
                    b.HasOne("JoinDev.Domain.Entities.Link", null)
                        .WithOne()
                        .HasForeignKey("JoinDev.Domain.Entities.UserLink", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("JoinDev.Domain.Entities.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectRestrictedInfo");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.ProjectRestrictedInfo", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("JoinDev.Domain.Entities.User", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("ProjectsAsCreator");
                });
#pragma warning restore 612, 618
        }
    }
}
